#!/usr/bin/env bash
# script prints type and destination of subdomains
print_subdomain () {
    record=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '/IN/ { print $4 }')
    ipAdd=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '/IN/ { print $5 }')
    echo "The subdomain $2 is a $record record and points to $ipAdd"
    }

if [ $# -eq 2 ]
then
    print_subdomain "$1" "$2"
elif [ $# -eq 1 ]
then
    print_subdomain "$1" "www"
    print_subdomain "$1" "lb-01"
    print_subdomain "$1" "web-01"
    print_subdomain "$1" "web-02"
fi
